In [4]:
#imports
import numpy as np
from ISLP import load_data

In [6]:
#Data
auto = load_data('Auto')
auto

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
387,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
388,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
389,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
390,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
391,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [7]:
#qualitative vs quantitative predictors

# List quantitative (numeric) column names
quantitative_columns = auto.select_dtypes(include=['int64', 'float64']).columns.tolist()

# List qualitative (categorical) column names
qualitative_columns = auto.select_dtypes(include=['object']).columns.tolist()

# Print the lists
print("Quantitative Columns:", quantitative_columns)
print("Qualitative Columns:", qualitative_columns)

Quantitative Columns: ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'year', 'origin']
Qualitative Columns: ['name']

In [8]:
# Calculate the range for each quantitative predictor
ranges = {column: np.ptp(auto[column]) for column in auto.select_dtypes(include=['int64', 'float64']).columns}

# Print the ranges
for predictor, predictor_range in ranges.items():
    print(f"Range of {predictor}: {predictor_range}")

Range of mpg: 37.6
Range of cylinders: 5
Range of displacement: 387.0
Range of horsepower: 184
Range of weight: 3527
Range of acceleration: 16.8
Range of year: 12
Range of origin: 2

In [9]:
#mean and standard deviation
statistics = {
    'Mean': auto[quantitative_columns].mean(),
    'Standard Deviation': auto[quantitative_columns].std()
}

# Print the statistics
for stat_type, values in statistics.items():
    print(f"\n{stat_type} of each quantitative predictor:")
    for predictor, value in values.items():
        print(f"{predictor}: {value}")

Mean of each quantitative predictor:
mpg: 23.44591836734694
cylinders: 5.471938775510204
displacement: 194.41198979591837
horsepower: 104.46938775510205
weight: 2977.5841836734694
acceleration: 15.541326530612228
year: 75.9795918367347
origin: 1.5765306122448979

Standard Deviation of each quantitative predictor:
mpg: 7.805007486571799
cylinders: 1.7057832474527843
displacement: 104.64400390890465
horsepower: 38.49115993282855
weight: 849.4025600429496
acceleration: 2.7588641191880816
year: 3.6837365435778278
origin: 0.805518183418305

In [12]:
# Remove the 10th through 85th observations
df_subset = auto.drop(auto.index[9:84])

# Calculate the range, mean, and standard deviation for each predictor in the subset
quantitative_columns = df_subset.select_dtypes(include=['int64', 'float64']).columns

statistics_subset = {
    'Range': np.ptp(df_subset[quantitative_columns], axis=0),
    'Mean': np.mean(df_subset[quantitative_columns], axis=0),
    'Standard Deviation': np.std(df_subset[quantitative_columns], axis=0)
}

# Print the statistics for the subset
for stat_type, values in statistics_subset.items():
    print(f"\n{stat_type} of each predictor in the subset:")
    for i, predictor in enumerate(quantitative_columns):
        print(f"{predictor}: {values[i]}")

Range of each predictor in the subset:
mpg: 35.6
cylinders: 5.0
displacement: 387.0
horsepower: 184.0
weight: 3348.0
acceleration: 16.3
year: 12.0
origin: 2.0

Mean of each predictor in the subset:
mpg: 24.368454258675072
cylinders: 5.381703470031546
displacement: 187.7539432176656
horsepower: 100.95583596214512
weight: 2939.643533123028
acceleration: 15.71829652996845
year: 77.13249211356467
origin: 1.5993690851735016

Standard Deviation of each predictor in the subset:
mpg: 7.868458084431573
cylinders: 1.655517379007591
displacement: 99.78173036550804
horsepower: 35.83890444223678
weight: 811.3668350814979
acceleration: 2.689560305630277
year: 3.1051170402311743
origin: 0.8180145884583646